"""Add database-generated identities to bigint primary keys.

Revision ID: 0005_bigint_identity
Revises: 0004_typed_media_sources
Create Date: 2026-08-31

"""
from typing import Sequence, Union

from alembic import op


revision: str = "0005_bigint_identity"
down_revision: Union[str, Sequence[str], None] = "0004_typed_media_sources"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_TABLES = ("users", "media", "genres", "user_media", "media_sources")


def upgrade() -> None:
    for table in _TABLES:
        op.execute(
            f'ALTER TABLE "{table}" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY'
        )


def downgrade() -> None:
    for table in _TABLES:
        op.execute(
            f'ALTER TABLE "{table}" ALTER COLUMN id DROP IDENTITY IF EXISTS'
        )
